### ISSUE TITLE
The game opens but in background

### ISSUE THREAD

**Issue by RelicsareLost** [fkortsagin/Max-Payne-2-Fix-Windows-11#1]
![image](https://user-images.githubusercontent.com/81030697/224917848-600d4985-893e-458f-9889-134b0b1184b7.png)
I have copy and pasted the files in directory but when I click on it nothing happens except for it running in the background and you can see the .exe running in task manager. I cant switch to the game even with alt+tab for it doesnt even show up.

(edit: problems fixed! just reinstalled net frameworks)

**Comment by silentgameplays** [comment]
> ![image](https://user-images.githubusercontent.com/81030697/224917848-600d4985-893e-458f-9889-134b0b1184b7.png) I have copy and pasted the files in directory but when I click on it nothing happens except for it running in the background and you can see the .exe running in task manager. I cant switch to the game even with alt+tab for it doesnt even show up.

Have you installed the prerequisites,described in the readme? 

**For DX8 and older NET Framerworks required for old software and games:**

Go to Control Panel>Programs>Programs and Features>Turn Windows Features on or off>Legacy Components>Enable Direct Play .NET 3.5 Framework support

If something is still borked,install this:
Install DirectX 9 Runtime from MS on Windows 11 it is not included:
https://www.microsoft.com/en-us/download/details.aspx?id=8109

Also on older laptops make sure you are using NVIDIA/AMD GPU instead of Intel integrated by adjusting the settings in the Control Panel of your GPU.

**Comment by RelicsareLost** [comment]
thank you kind sir
after reinstalling and installing the net frameworks it works well.

**Comment by silentgameplays** [comment]
Thank you for the great feedback! Glad it works,enjoy the classic!
